### ISSUE TITLE
Question Enum

### ISSUE THREAD

**Issue by DeadlyKom** [sjasmplus/sjasmplus#18]
Hello, I wanted to write to support, but I only found a bug report.
I have a question about the possibility of creating automatic enumerators for constant values, is it possible to organize this somehow?

example:

```
       autonumber 10, +1   ; (enum)
A      EQU 
B      EQU
C      EQU
       endauto
```
        
result:
```
A = 10
B = 11
C = 12
```

The first argument is the first value of the constant, the second is the step from the first value (it can be either positive or negative)

P/S Sometimes you have to swap constants, and overwrite the values ​​by hand, it's not very convenient... 

Thanks in advance

**Comment by mkoloberdin** [comment]
Something like this using the ([existing syntax](https://github.com/sjasmplus/sjasmplus/wiki#macros)) should work to achieve what you want:
```
  MACRO ENUM_INIT VALUE, STEP
ENUM_VALUE=VALUE
ENUM_STEP=STEP
  ENDM

    MACRO ENUM L
L:    EQU ENUM_VALUE
ENUM_VALUE = ENUM_VALUE + ENUM_STEP
    ENDM
```

Usage:
```
  ENUM_INIT 10, 1
  ENUM A
  ENUM B
  ENUM C
```
