### ISSUE TITLE
Ошибка sjio.cpp:289:35: error: ‘relative’ is not a member of ‘fs’

### ISSUE THREAD

**Issue by asve79** [sjasmplus/sjasmplus#7]
При компиляции обновленной версии теперь падает так:

```
[ 81%] Building CXX object CMakeFiles/sjasmplus.dir/sjasm/sjio.cpp.o
/home/asve/sjasmplus/sjasm/sjio.cpp: In function ‘void OpenFile(const boost::filesystem::path&)’:
/home/asve/sjasmplus/sjasm/sjio.cpp:289:35: error: ‘relative’ is not a member of ‘fs’
         global::CurrentFilename = fs::relative(FileName, global::MainSrcFileDir);
                                   ^
/home/asve/sjasmplus/sjasm/sjio.cpp: In function ‘void includeFile(const boost::filesystem::path&)’:
/home/asve/sjasmplus/sjasm/sjio.cpp:331:50: error: ‘const class boost::filesystem::path’ has no member named ‘size’
                 IncFileName.string()[IncFileName.size() - 1] == '>';
                                                  ^
CMakeFiles/sjasmplus.dir/build.make:686: ошибка выполнения рецепта для цели «CMakeFiles/sjasmplus.dir/sjasm/sjio.cpp.o»
make[2]: *** [CMakeFiles/sjasmplus.dir/sjasm/sjio.cpp.o] Ошибка 1
CMakeFiles/Makefile2:72: ошибка выполнения рецепта для цели «CMakeFiles/sjasmplus.dir/all»
make[1]: *** [CMakeFiles/sjasmplus.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

```

```
Ubuntu linux
cmake version 3.14.0-rc2
~/dev/z80-wc_test$ sudo apt-get install libboost-filesystem-dev
Уже установлен пакет libboost-filesystem-dev самой новой версии (1.58.0.1ubuntu1).
```

**Comment by mkoloberdin** [comment]
Обновить эту древнюю ОС/boost никак не возможно?
https://www.boost.org/doc/libs/1_69_0/libs/filesystem/doc/release_history.html
> 1.60.0
>New: Added functions lexically_normal, lexically_relative, **relative**, and weakly_canonical. Many thanks to  Jamie Allsop for his help and perseverance. Resolves tickets #1976, #5897, #6249

Если нет, сегодня позже посмотрю что можно сделать...

**Comment by asve79** [comment]
Так-то нет ничего невозможного, но тогда надо понимать какую версию ставить. Другое дело что не только у меня может так спотыкаться при стандартных для убунты либах. Форк от z00m128 компилится норм.

**Comment by mkoloberdin** [comment]
Ubuntu 16.04 вышла уже почти 4 года назад. Не ожидал я что кто-то такую древность станет до сих пор использовать ;)

**Comment by asve79** [comment]
Хм...  Дык работает же. ) Хоть и оффтопик, но отмечу что после этих слов задумался не обновиться ли. ) Но ведь работает же )
В любом случае, если нужны более свежие либы, то все-таки укажи версию с которой компиляция нормально идет.

**Comment by mkoloberdin** [comment]
Добавил версию в ReadMe.
Посмотри ChangeLog Boost по ссылке выше, там довольно много багов исправлено, стоит обновить в любом случае по-моему.

**Comment by mkoloberdin** [comment]
OK, сделал чтоб работало со старыми версиями Boost.
В сообщениях об ошибках будут всегда полные пути файлов (как если бы было указано --fullpath), но в остальном будет работать точно так же.
