### ISSUE TITLE
Откомпилированые бинари w32 и w64

### ISSUE THREAD

**Issue by asve79** [sjasmplus/sjasmplus#9]
Волею судеб пришлось пересесть на win и оказалось что забилдить проект под win не так уж и просто. 
Пожелание:
Выкладывайте в проект скомпилированые бинари для w32 и w64.

**Comment by mkoloberdin** [comment]
Лежат же вот здесь бинарники: https://github.com/sjasmplus/sjasmplus/releases
А в чем именно проблема с компиляцией?

**Comment by asve79** [comment]
Эхх, вот век живи век учись! Спасибо за ссылку!

По проблеме с компиляцией:

- ставлю VS, ставлю cmake, ставлю boost.
- создаю в проекте папку build
- открываю cmake, указываю билд каталог и каталог с сырцами.
- запускаю сборку - cmake ругается что не найдена VS. Почитал что нужно доставить. Все галки норм протыканы. Т.к. на VS я не пишу то рабор проблемы получается оч долгим и малоинтересным. 

Но.. Раз есть бинари, то все эти приседания не актуальны! Спасибо еще раз!

**Comment by mkoloberdin** [comment]
Добавил в [README](https://github.com/sjasmplus/sjasmplus/blob/master/README.md) инструкцию (пример) по сборке в Visual Studio.
